# Generated by Django 3.2.3 on 2021-06-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('mass', models.CharField(blank=True, max_length=10, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=20, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=20, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('rotation_period', models.CharField(max_length=40, null=True)),
                ('orbital_period', models.CharField(max_length=40, null=True)),
                ('diameter', models.CharField(max_length=40, null=True)),
                ('climate', models.CharField(max_length=40, null=True)),
                ('gravity', models.CharField(max_length=40, null=True)),
                ('terrain', models.CharField(max_length=40, null=True)),
                ('surface_water', models.CharField(max_length=40, null=True)),
                ('population', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('model', models.CharField(max_length=40, null=True)),
                ('manufacturer', models.CharField(max_length=80, null=True)),
                ('cost_in_credits', models.CharField(max_length=40, null=True)),
                ('length', models.CharField(max_length=40, null=True)),
                ('max_atmosphering_speed', models.CharField(max_length=40, null=True)),
                ('crew', models.CharField(max_length=40, null=True)),
                ('passengers', models.CharField(max_length=40, null=True)),
                ('cargo_capacity', models.CharField(max_length=40, null=True)),
                ('consumables', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('classification', models.CharField(max_length=40, null=True)),
                ('designation', models.CharField(max_length=40, null=True)),
                ('average_height', models.CharField(max_length=40, null=True)),
                ('skin_colors', models.CharField(max_length=200, null=True)),
                ('hair_colors', models.CharField(max_length=200, null=True)),
                ('eye_colors', models.CharField(max_length=200, null=True)),
                ('average_lifespan', models.CharField(max_length=40, null=True)),
                ('language', models.CharField(max_length=40, null=True)),
                ('homeworld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.planet')),
                ('people', models.ManyToManyField(null=True, related_name='species', to='app.People')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='app.planet'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.transport')),
                ('vehicle_class', models.CharField(max_length=40, null=True)),
                ('pilots', models.ManyToManyField(blank=True, null=True, related_name='vehicles', to='app.People')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.transport',),
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.transport')),
                ('hyperdrive_rating', models.CharField(max_length=40, null=True)),
                ('MGLT', models.CharField(max_length=40, null=True)),
                ('starship_class', models.CharField(max_length=40, null=True)),
                ('pilots', models.ManyToManyField(blank=True, null=True, related_name='starships', to='app.People')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.transport',),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('episode_id', models.IntegerField(null=True)),
                ('opening_crawl', models.TextField(max_length=1000, null=True)),
                ('director', models.CharField(max_length=100, null=True)),
                ('producer', models.CharField(max_length=100, null=True)),
                ('release_date', models.DateField(null=True)),
                ('characters', models.ManyToManyField(blank=True, null=True, related_name='films', to='app.People')),
                ('planets', models.ManyToManyField(blank=True, null=True, related_name='films', to='app.Planet')),
                ('species', models.ManyToManyField(blank=True, null=True, related_name='films', to='app.Species')),
                ('starships', models.ManyToManyField(blank=True, null=True, related_name='films', to='app.Starship')),
                ('vehicles', models.ManyToManyField(blank=True, null=True, related_name='films', to='app.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
